name: Auto Pull Request on feat commit

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mvn clean install
          mvn compile

      - name: Create PR if commit starts with feat
        if: startsWith(github.event.head_commit.message, 'feat:')
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Auto PR for feat commit'
          title: 'Auto Pull Request'
          branch: develop
