name: Auto Pull Request on Master by Develop

on:
  push:
    branches:
      - develop

jobs:
  auto_pr_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
            mvn clean test
            mvn jacoco:report

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Check Coverage and Print Result
        run: |
          if [ "$coverage" -gt "70" ]; then
            echo "Pode passar!"
          else
            echo "Não pode passar!"
          fi
