name: Auto Pull Request on feat commit

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  auto_pr_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mvn clean install

      - name: Create PR
        run: |
            # Obter o nome da branch
            branch_name=$(git branch --show-current)
            
            # Crie um novo Pull Request usando a API do GitHub
            response=$(curl -X POST \
              -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls \
              -d '{
                "title": "Auto Pull Request",
                "head": "develop",
                "base": "'$branch_name'"
              }')
            
            # Imprima a URL do PR criado
            echo "Pull Request URL: $(echo $response | jq -r .html_url)"